### ISSUE TITLE
SST26 Documentation Error

### ISSUE THREAD

**Issue by wesley5040** [Microchip-MPLAB-Harmony/core#16]
The `DRV_SST26_Read` function documentation specifies that it is a blocking command, but I had issues with the data not being in the buffer, but once I treated it as non-blocking it worked as expected.

Example:
```
// Not working
DRV_SST26_Read(handle, buffer, len, addr);
// Accessing the data here results in getting incorrect data

// Working
DRV_SST26_Read(handle, buffer, len, addr);
for (; DRV_SST26_TransferStatusGet(handle) == DRV_SST26_TRANSFER_BUSY;);
// Accessing the data here works as expected
```

Tested on a PIC32MZ2064DAR169 with SST26VF064BT, with core v3.6.1.

**Comment by amitraddi** [comment]
@wesley5040 Thanks for reporting the issue.
This API is common for both QSPI peripheral library and SQI peripheral library.

When using QSPI peripheral library on SAM devices the behavior is blocking.
When using SQI peripheral library on PIC32M devices it's non blocking as it uses internal DMA.
The working code you mentioned is correct way of using for PIC32 devices.

The documentation will be fixed in next release.

**Comment by wesley5040** [comment]
Thanks.
